# 🔢 Day 25 — Introduction to NumPy
### Data Analytics Using Python | NAVTTC Skills Development Program

---

**Topics Covered Today:**
- ✅ What is NumPy and why use it?
- ✅ Creating arrays — all methods
- ✅ Array attributes: shape, ndim, dtype, size
- ✅ Indexing, slicing, and boolean filtering
- ✅ Array operations — vectorized computing
- ✅ NumPy statistics: mean, median, std, percentile
- ✅ Reshaping, sorting, where(), unique()
- ✅ Practice project: Student Exam Analysis

**Duration:** 2.5 Hours

---

> 💡 **How to use this notebook:**
> - Read every explanation **before** running code
> - Press **Shift + Enter** to run a cell
> - Try changing the values — experimenting is the fastest way to learn
> - NumPy is the **foundation** of Pandas, Matplotlib, and machine learning

---
## 🧠 Why NumPy? The Problem With Plain Python Lists

Imagine you have salary data for 1,000 employees and need to apply a 10% tax to every value.

**With a Python list — you must loop:**
```python
salaries = [50000, 80000, 65000, ...]  # 1000 items
after_tax = []
for s in salaries:
    after_tax.append(s * 0.90)
# Works, but SLOW — Python processes one item at a time
```

**With NumPy — one line, runs in C:**
```python
import numpy as np
salaries   = np.array([50000, 80000, 65000, ...])
after_tax  = salaries * 0.90   # Applied to ALL 1000 at once!
```

### Why NumPy is faster:
```
Python List           NumPy Array
─────────────────     ──────────────────────
Each item is a        All items stored as
Python object in      raw bytes in one
separate memory       contiguous block
locations             → CPU can process in
→ Slow to loop        parallel (vectorized)
```

**Speed difference in practice:** NumPy can be **25–100× faster** than Python loops for numerical operations.

---
# 📦 SECTION 1: Importing NumPy & Creating Arrays

In [ ]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
# ── Always import NumPy as 'np' — this is the universal convention ─────────
# Every data scientist in the world writes 'import numpy as np'
# Never write 'import numpy' alone — you'd have to type numpy.array() everywhere

import numpy as np

print(f"NumPy version: {np.__version__}")
print("NumPy imported successfully! ✅")

NumPy version: 2.4.3
NumPy imported successfully! ✅


### 1.1 — Creating Arrays: np.array()

In [8]:
marks = [10, 20, 30, 40, 50]
marks_array = np.array(marks)

print(marks_array)
print(type(marks_array))
print(marks_array.dtype)

[10 20 30 40 50]
<class 'numpy.ndarray'>
int64


In [3]:
# ── np.array() — Convert a Python list into a NumPy array ─────────────────
# This is the most common way to create an array

# 1D array — a single row of numbers
scores = np.array([85, 92, 78, 95, 88, 73, 61, 90])
print("1D Array:")
print(scores)
print(f"Type: {type(scores)}")
print()

# 2D array — rows and columns (like a table/spreadsheet)
# Each inner list = one row
marks_table = np.array([
    [85, 92, 78],    # Ahmed:  Math, English, Python
    [90, 88, 95],    # Fatima: Math, English, Python
    [70, 65, 80],    # Zara:   Math, English, Python
    [55, 60, 72],    # Hassan: Math, English, Python
])
print("2D Array (4 students x 3 subjects):")
print(marks_table)
print()

# Float array — when you include a decimal, entire array becomes float
prices = np.array([1200.50, 850.00, 3500.75, 200.25])
print(f"Float array : {prices}")
print(f"Data type   : {prices.dtype}")

# String array — stores text
cities = np.array(["Islamabad", "Lahore", "Karachi", "Peshawar"])
print(f"String array: {cities}")
print(f"Data type   : {cities.dtype}")

1D Array:
[85 92 78 95 88 73 61 90]
Type: <class 'numpy.ndarray'>

2D Array (4 students x 3 subjects):
[[85 92 78]
 [90 88 95]
 [70 65 80]
 [55 60 72]]

Float array : [1200.5   850.   3500.75  200.25]
Data type   : float64
String array: ['Islamabad' 'Lahore' 'Karachi' 'Peshawar']
Data type   : <U9


### 1.2 — Creating Arrays: Special Functions

In [12]:
dim1 = np.zeros(3)
print(dim1)
print()
dim2 = np.zeros((2,3))
print(dim2)

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# ── np.zeros() — Array filled with 0s ─────────────────────────────────────
# Use when you want to create an empty container to fill later
zeros_1d = np.zeros(6)
zeros_2d = np.zeros((3, 4))    # 3 rows, 4 columns — pass as a tuple!

print("np.zeros(6)   :", zeros_1d)
print("np.zeros(3,4) :")
print(zeros_2d)
print()

# ── np.ones() — Array filled with 1s ──────────────────────────────────────
ones_1d = np.ones(5)
ones_2d = np.ones((2, 3))
print("np.ones(5)    :", ones_1d)
print("np.ones(2,3)  :")
print(ones_2d)
print()

# ── np.full() — Array filled with a specific value ────────────────────────
# Useful for initializing with a default value
passing_mark = np.full(5, 60)            # 5 elements all equal to 60
salary_base  = np.full((2, 3), 50000)   # 2×3 grid all 50000
print("np.full(5, 60)       :", passing_mark)
print("np.full((2,3), 50000):")
print(salary_base)

np.zeros(6)   : [0. 0. 0. 0. 0. 0.]
np.zeros(3,4) :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones(5)    : [1. 1. 1. 1. 1.]
np.ones(2,3)  :
[[1. 1. 1.]
 [1. 1. 1.]]

np.full(5, 60)       : [60 60 60 60 60]
np.full((2,3), 50000):
[[50000 50000 50000]
 [50000 50000 50000]]


In [16]:
num100 = np.arange(100)
print(num100)

num25_60 = np.arange(25,61)
print(num25_60)

num = np.arange(10,101,5)
print(num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [28]:
# ── np.arange() — Like Python's range() but returns a NumPy array ─────────
# Syntax: np.arange(start, stop, step)   — stop is EXCLUDED

arr1 = np.arange(10)              # 0 to 9
arr2 = np.arange(1, 11)           # 1 to 10
arr3 = np.arange(0, 50, 10)       # 0, 10, 20, 30, 40
arr4 = np.arange(0.0, 1.0, 0.2)   # decimals work too!

print(f"arange(10)         : {arr1}")
print(f"arange(1, 11)      : {arr2}")
print(f"arange(0, 50, 10)  : {arr3}")
print(f"arange(0, 1, 0.2)  : {arr4}")
print()

# ── np.linspace() — Evenly spaced values between start and stop ───────────
# KEY DIFFERENCE from arange: you specify HOW MANY values you want
# Both start AND stop are INCLUDED

marks_scale  = np.linspace(0, 100, 5)     # 5 evenly spaced from 0 to 100
temp_range   = np.linspace(20, 45, 6)     # 6 temps from 20°C to 45°C
percent_grad = np.linspace(0, 1, 11)      # 0%, 10%, 20%...100%

print(f"linspace(0, 100, 5)  : {marks_scale}")
print(f"linspace(20, 45, 6)  : {temp_range}")
print(f"linspace(0, 1, 11)   : {percent_grad}")


arange(10)         : [0 1 2 3 4 5 6 7 8 9]
arange(1, 11)      : [ 1  2  3  4  5  6  7  8  9 10]
arange(0, 50, 10)  : [ 0 10 20 30 40]
arange(0, 1, 0.2)  : [0.  0.2 0.4 0.6 0.8]

linspace(0, 100, 5)  : [  0.  25.  50.  75. 100.]
linspace(20, 45, 6)  : [20. 25. 30. 35. 40. 45.]
linspace(0, 1, 11)   : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [75]:
np.random.seed(4)
rand_floats = np.random.rand(5)
print(f"rand(5)         : {rand_floats.round(4)}")

# Random integers between a range
rand_int    = np.random.randint(60, 100, size=8)   # 8 scores between 60 and 99
print(f"randint(60,100,8): {rand_int}")

rand(5)         : [0.967  0.5472 0.9727 0.7148 0.6977]
randint(60,100,8): [99 90 96 98 63 60 81 81]


In [78]:
rand_floats = np.random.rand(5)
print(f"rand(5)         : {rand_floats.round(4)}")

# Random integers between a range
rand_int    = np.random.randint(60, 100, size=8)  
print(f"randint(60,100,8): {rand_int}")

rand(5)         : [0.7674 0.179  0.3756 0.5025 0.6867]
randint(60,100,8): [81 90 75 96 87 68 97 68]


In [ ]:
# ── np.random — Random number generation ──────────────────────────────────
# IMPORTANT: Set a seed for reproducibility — same seed = same random numbers
# np.random.seed(42)   # Any integer works — ensures your results are reproducible

# Random floats between 0 and 1
rand_floats = np.random.rand(5)
print(f"rand(5)         : {rand_floats.round(4)}")

# Random integers between a range
rand_int    = np.random.randint(60, 100, size=8)   # 8 scores between 60 and 99
print(f"randint(60,100,8): {rand_int}")

# Random 2D array — useful for generating test datasets
rand_matrix = np.random.randint(50, 100, size=(4, 3))
print("\nRandom 4x3 marks table:")
print(rand_matrix)

# Normal distribution — bell curve, mean=0, std=1
normal_data = np.random.randn(6).round(2)
print(f"\nNormal distribution: {normal_data}")

rand(5)         : [0.3745 0.9507 0.732  0.5987 0.156 ]
randint(60,100,8): [78 82 70 70 83 95 99 83]

Random 4×3 marks table:
[[52 71 51]
 [73 93 79]
 [87 51 70]
 [82 61 71]]

Normal distribution: [-2.44  0.6  -0.25 -0.16 -1.48  1.49]


---
# 📐 SECTION 2: Array Attributes — shape, ndim, dtype, size

Every NumPy array has **attributes** — properties that describe it. These are not functions (no parentheses), just values attached to the array.

In [ ]:
# ── Array attributes ───────────────────────────────────────────────────────

# Create a 2D array — 4 students × 4 subjects
exam_data = np.array([
    [85, 92, 78, 88],    # Ahmed
    [90, 88, 95, 82],    # Fatima
    [70, 65, 80, 75],    # Zara
    [55, 60, 72, 58],    # Hassan
])

print("Array:")
print(exam_data)
print()

# ── The 5 most important attributes ───────────────────────────────────────
print(f"shape  : {exam_data.shape}")
# → (4, 3) means 4 rows and 3 columns — ALWAYS (rows, columns)

print(f"ndim   : {exam_data.ndim}")
# → 2 means it's a 2-dimensional array (like a table)

print(f"dtype  : {exam_data.dtype}")
# → int64 means 64-bit integer — the data type of every element

print(f"size   : {exam_data.size}")
# → 16 = total number of elements = 4 rows × 4 cols

print(f"len()  : {len(exam_data)}")
# → 4 = length of FIRST dimension only (number of rows)
# WARNING: len() does NOT give total elements — use .size for that!

print()
print("=" * 42)
print(f"Interpretation: {exam_data.shape[0]} students x {exam_data.shape[1]} subjects")
print(f"Total data points: {exam_data.size}")

In [ ]:
# ── dtype — Data types in NumPy ────────────────────────────────────────────
# NumPy automatically picks a dtype, but you can specify it
# Choosing the right dtype saves memory for large datasets

int_arr   = np.array([1, 2, 3, 4])                          # default: int64
float_arr = np.array([1.5, 2.5, 3.5])                       # default: float64
int8_arr  = np.array([1, 2, 3], dtype=np.int8)              # tiny: values -128 to 127
float32   = np.array([1.5, 2.5, 3.5], dtype=np.float32)    # half the memory of float64

print(f"int_arr   dtype: {int_arr.dtype}")
print(f"float_arr dtype: {float_arr.dtype}")
print(f"int8_arr  dtype: {int8_arr.dtype}")
print(f"float32   dtype: {float32.dtype}")
print()

# Type conversion — change dtype after creation
converted = int_arr.astype(float)    # int → float
print(f"Original  : {int_arr}    dtype: {int_arr.dtype}")
print(f"Converted : {converted}  dtype: {converted.dtype}")

---
# 🔍 SECTION 3: Indexing, Slicing & Boolean Filtering

## How indexing works in NumPy:

```
arr = [10, 20, 30, 40, 50, 60]

Positive index:  0    1    2    3    4    5
                ┌────┬────┬────┬────┬────┬────┐
                │ 10 │ 20 │ 30 │ 40 │ 50 │ 60 │
                └────┴────┴────┴────┴────┴────┘
Negative index:  -6   -5   -4   -3   -2   -1

arr[2]   → 30      arr[-1]  → 60      arr[-2]  → 50
arr[1:4] → [20,30,40]      arr[::-1] → [60,50,40,30,20,10]
```

In [ ]:
# ── 1D Indexing & Slicing ──────────────────────────────────────────────────

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(f"Original array: {arr}")
print()

# Single element
print(f"arr[0]      = {arr[0]}      # first element")
print(f"arr[-1]     = {arr[-1]}      # last element")
print(f"arr[4]      = {arr[4]}      # index 4")
print()

# Slicing [start : stop : step]   — stop is EXCLUDED
print(f"arr[2:6]    = {arr[2:6]}    # index 2 to 5")
print(f"arr[:4]     = {arr[:4]}        # first 4 elements")
print(f"arr[5:]     = {arr[5:]}        # from index 5 to end")
print(f"arr[::2]    = {arr[::2]}        # every 2nd element")
print(f"arr[1::2]   = {arr[1::2]}        # every 2nd, starting at 1")
print(f"arr[::-1]   = {arr[::-1]}  # reversed!")

In [ ]:
# ── 2D Indexing — arr[row, column] ────────────────────────────────────────
# This is fundamentally different from nested Python lists!
# List of lists: matrix[0][1]   vs   NumPy: matrix[0, 1]

matrix = np.array([
    [10, 20, 30, 40],    # row 0
    [50, 60, 70, 80],    # row 1
    [90,100,110,120],    # row 2
])

print("Matrix:")
print(matrix)
print()

# Single elements
print(f"matrix[0, 0]   = {matrix[0, 0]}    # row 0, col 0")
print(f"matrix[1, 2]   = {matrix[1, 2]}    # row 1, col 2")
print(f"matrix[-1, -1] = {matrix[-1, -1]}   # last row, last col")
print()

# Full rows and columns
print(f"matrix[1, :]   = {matrix[1, :]}      # entire row 1")
print(f"matrix[:, 0]   = {matrix[:, 0]}          # entire column 0")
print(f"matrix[:, 2]   = {matrix[:, 2]}      # entire column 2")
print()

# Sub-matrix (a portion of the 2D array)
print("matrix[0:2, 1:3] — top-right 2x2 block:")
print(matrix[0:2, 1:3])

In [6]:
# ── Boolean Indexing — The Most Powerful Feature ───────────────────────────
# Pass a condition as the index — returns only elements where condition is True
# This is HOW data analysts FILTER data — no loops needed!

scores = np.array([85, 42, 96, 73, 58, 91, 67, 38, 78, 55])
print(f"All scores : {scores}")
print()

# Step 1: The condition creates a boolean array (True/False mask)
mask = scores >= 70
print(f"scores >= 70 mask: {mask}")
print()

# Step 2: Use the mask to filter
passing   = scores[scores >= 70]
failing   = scores[scores < 60]
top_marks = scores[scores >= 90]
print(f"Passing (≥70)  : {passing}")
print(f"Failing  (<60) : {failing}")
print(f"Top marks (≥90): {top_marks}")
print()

# Combining conditions with & (AND) and | (OR)
# ⚠️ Must use & and | with NumPy — not 'and' / 'or'
# ⚠️ Must wrap each condition in parentheses!
merit = scores[(scores >= 70) & (scores < 90)]
extremes = scores[(scores < 50) | (scores >= 95)]
print(f"Merit (70-89)     : {merit}")
print(f"Extremes (<50|≥95): {extremes}")

All scores : [85 42 96 73 58 91 67 38 78 55]

scores >= 70 mask: [ True False  True  True False  True False False  True False]

Passing (≥70)  : [85 96 73 91 78]
Failing  (<60) : [42 58 38 55]
Top marks (≥90): [96 91]

Merit (70-89)     : [85 73 78]
Extremes (<50|≥95): [42 96 38]


---
# ⚡ SECTION 4: Array Operations — Vectorized Computing

**Vectorization** means: instead of looping through each element, the operation is applied to the entire array at once — at C speed.

In [ ]:
# ── Element-wise arithmetic ────────────────────────────────────────────────
# When two arrays have the same shape, operations work element by element

revenue  = np.array([82000, 95000, 110000, 125000, 140000])  # PKR
expenses = np.array([45000, 52000,  61000,  68000,  72000])  # PKR

profit       = revenue - expenses           # element-wise subtraction
profit_margin= (profit / revenue) * 100     # element-wise division & multiply

print(f"Revenue      : {revenue}")
print(f"Expenses     : {expenses}")
print(f"Profit       : {profit}")
print(f"Margin (%)   : {profit_margin.round(1)}")
print()

# All arithmetic operators work
a = np.array([10, 20, 30, 40])
b = np.array([ 2,  4,  5,  8])

print(f"a + b  = {a + b}")
print(f"a - b  = {a - b}")
print(f"a * b  = {a * b}")
print(f"a / b  = {a / b}")
print(f"a // b = {a // b}   # floor division")
print(f"a % b  = {a % b}    # modulus")
print(f"a ** 2 = {a ** 2}   # power")

In [ ]:
# ── Scalar Operations — Broadcasting ──────────────────────────────────────
# A scalar (single number) is automatically 'broadcast' to match array shape
# This is called BROADCASTING — NumPy stretches the scalar to fit

salaries = np.array([50000, 80000, 65000, 45000, 95000])

# Apply 10% tax — no loop needed!
after_tax     = salaries * 0.90
# Add PKR 5000 bonus to everyone
with_bonus    = salaries + 5000
# Apply 15% raise for all
after_raise   = (salaries * 1.15).astype(int)

print(f"Original   : {salaries}")
print(f"After tax  : {after_tax}")
print(f"With bonus : {with_bonus}")
print(f"After raise: {after_raise}")
print()

# ── Universal Functions (ufuncs) ───────────────────────────────────────────
# NumPy has mathematical functions that work on entire arrays

values = np.array([1, 4, 9, 16, 25, 36])

print(f"np.sqrt()  : {np.sqrt(values)}")
print(f"np.abs()   : {np.abs(np.array([-3, -1, 0, 2, -5]))}")
print(f"np.log()   : {np.log(values).round(3)}")
print(f"np.floor() : {np.floor(np.array([1.2, 2.7, 3.9]))}")
print(f"np.ceil()  : {np.ceil(np.array([1.2, 2.7, 3.9]))}")
print(f"np.round() : {np.round(np.array([1.456, 2.789, 3.123]), 2)}")

---
# 📊 SECTION 5: NumPy Statistics

These are the functions you will use **every single day** as a data analyst. NumPy's statistical functions are the core of all data summarization.

In [ ]:
# ── Core statistics on 1D array ────────────────────────────────────────────

# Real exam scores — 15 students from Islamabad batch
scores = np.array([72, 85, 90, 60, 78, 95, 55, 88, 73, 82, 91, 67, 77, 84, 69])

print("=" * 50)
print("       CLASS STATISTICS REPORT")
print("=" * 50)
print(f"  Count            : {len(scores)} students")
print(f"  Mean (Average)   : {np.mean(scores):.2f}")
print(f"  Median           : {np.median(scores)}")
print(f"  Std Deviation    : {np.std(scores):.2f}")
print(f"  Variance         : {np.var(scores):.2f}")
print(f"  Minimum          : {np.min(scores)}")
print(f"  Maximum          : {np.max(scores)}")
print(f"  Total (Sum)      : {np.sum(scores)}")
print(f"  Range            : {np.max(scores) - np.min(scores)}")
print("-" * 50)
print(f"  25th Percentile  : {np.percentile(scores, 25)}")
print(f"  50th Percentile  : {np.percentile(scores, 50)}  ← same as median")
print(f"  75th Percentile  : {np.percentile(scores, 75)}")
print("=" * 50)

In [ ]:
# ── Mean vs Median — When do they differ? ─────────────────────────────────
# This is a CRITICAL concept in data analysis

# Symmetric data — mean ≈ median
normal_incomes = np.array([50000, 55000, 60000, 65000, 70000])
print("Normal incomes (no outliers):")
print(f"  Mean   : PKR {np.mean(normal_incomes):,.0f}")
print(f"  Median : PKR {np.median(normal_incomes):,.0f}")
print()

# Skewed data — one outlier pulls the mean
skewed_incomes = np.array([50000, 55000, 60000, 65000, 1000000])  # one CEO added!
print("Skewed incomes (one very high earner):")
print(f"  Mean   : PKR {np.mean(skewed_incomes):,.0f}   ← pulled up by outlier")
print(f"  Median : PKR {np.median(skewed_incomes):,.0f}    ← not affected")
print()
print("Lesson: Use MEDIAN when data has outliers (income, house prices)")
print("        Use MEAN when data is roughly symmetric (exam scores, temperature)")

In [ ]:
# ── Statistics on 2D arrays — axis parameter ──────────────────────────────
# axis=0 means: compute DOWN each column (across rows)
# axis=1 means: compute ACROSS each row (across columns)
#
#        Math  English  Python  Stats     ← subjects (columns)
# Ahmed: [ 85,   92,     78,     88 ]  ← axis=1 goes across this row
# Fatima:[ 90,   88,     95,     82 ]
# Zara:  [ 70,   65,     80,     75 ]
#          ↑ axis=0 goes down this column

marks = np.array([
    [85, 92, 78, 88],    # Ahmed
    [90, 88, 95, 82],    # Fatima
    [70, 65, 80, 75],    # Zara
    [55, 60, 72, 58],    # Hassan
])

print("Marks matrix (4 students × 4 subjects):")
print(marks)
print()

# axis=1 → compute across columns (one result PER STUDENT)
student_avg = np.mean(marks, axis=1)
student_max = np.max(marks, axis=1)
print("Per student (axis=1):")
names = ["Ahmed", "Fatima", "Zara", "Hassan"]
for name, avg, mx in zip(names, student_avg, student_max):
    print(f"  {name:<8}: Average={avg:.2f}  Best={mx}")

print()

# axis=0 → compute down rows (one result PER SUBJECT)
subject_avg = np.mean(marks, axis=0)
subject_min = np.min(marks, axis=0)
subjects = ["Math", "English", "Python", "Stats"]
print("Per subject (axis=0):")
for subj, avg, mn in zip(subjects, subject_avg, subject_min):
    print(f"  {subj:<10}: Average={avg:.2f}  Lowest={mn}")

---
# 🔧 SECTION 6: Reshaping, Sorting & Useful Functions

In [ ]:
# ── reshape() — Change shape without changing data ─────────────────────────
# Rule: rows × columns MUST equal original size
# 12 elements can become (1,12), (2,6), (3,4), (4,3), (6,2), (12,1)

flat = np.arange(1, 13)   # [1, 2, 3, ... 12] — 12 elements
print(f"Original (1D): {flat}")
print()

matrix_3x4 = flat.reshape(3, 4)    # 3 rows, 4 cols = 12 ✅
matrix_4x3 = flat.reshape(4, 3)    # 4 rows, 3 cols = 12 ✅
matrix_2x6 = flat.reshape(2, 6)    # 2 rows, 6 cols = 12 ✅

print("reshape(3, 4):")
print(matrix_3x4)
print("\nreshape(4, 3):")
print(matrix_4x3)
print()

# -1 as a dimension → NumPy figures out the size automatically
auto_shape = flat.reshape(3, -1)   # 3 rows, figure out columns
print(f"reshape(3, -1) → shape: {auto_shape.shape}")
print(auto_shape)

# flatten() — reverse: any shape back to 1D
back_to_1d = matrix_3x4.flatten()
print(f"\nflatten()  : {back_to_1d}")

In [ ]:
# ── np.sort() and np.argsort() ─────────────────────────────────────────────

scores = np.array([78, 55, 92, 67, 88, 45, 91, 73])
print(f"Original : {scores}")

# np.sort() — returns a sorted COPY (original unchanged)
ascending  = np.sort(scores)
descending = np.sort(scores)[::-1]    # sort then reverse
print(f"Ascending : {ascending}")
print(f"Descending: {descending}")
print(f"Original unchanged: {scores}")
print()

# np.argsort() — returns INDICES that would sort the array
# Use this to rank students without changing the original order
rank_order = np.argsort(scores)[::-1]    # indices sorted by score, highest first
names = ["Ahmed", "Fatima", "Zara", "Hassan", "Sara", "Bilal", "Amina", "Tariq"]

print("Class ranking by score (highest first):")
for rank, idx in enumerate(rank_order, 1):
    print(f"  Rank {rank}: {names[idx]:<8} → {scores[idx]}")

In [ ]:
# ── np.where() — Conditional replacement (vectorized if/else) ─────────────
# Syntax: np.where(condition, value_if_true, value_if_false)
# Think of it as: for every element — if condition → true_val, else → false_val

scores = np.array([85, 42, 96, 73, 58, 91, 67, 38, 78, 55])

# Assign Pass/Fail
results = np.where(scores >= 60, "Pass", "Fail")
print(f"Scores  : {scores}")
print(f"Results : {results}")
print()

# Assign letter grades
grades = np.where(scores >= 90, "A",
         np.where(scores >= 80, "B",
         np.where(scores >= 70, "C",
         np.where(scores >= 60, "D", "F"))))

print("Detailed grading:")
for s, g in zip(scores, grades):
    print(f"  Score {s:3d}  →  {g}")

In [ ]:
# ── np.unique() — Find unique values and counts ────────────────────────────

grade_list = np.array(["A","B","C","A","B","A","D","C","B","A","F","B","A"])

# Just unique values
unique_grades = np.unique(grade_list)
print(f"Unique grades : {unique_grades}")

# Unique values AND their counts
values, counts = np.unique(grade_list, return_counts=True)
print("\nGrade Distribution:")
for grade, count in zip(values, counts):
    bar = "█" * count
    print(f"  {grade} : {bar} ({count})")

# ── np.concatenate() and np.vstack() ──────────────────────────────────────
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

joined    = np.concatenate([a, b])     # [1 2 3 4 5 6]
stacked   = np.vstack([a, b])          # 2D: [[1 2 3], [4 5 6]]
col_stack = np.column_stack([a, b])    # 2D: columns side by side

print(f"\nconcatenate : {joined}")
print(f"vstack      :\n{stacked}")
print(f"column_stack:\n{col_stack}")

---
# 🏆 SECTION 7: Practice Project — Student Exam Analysis

## Scenario:
You are a data analyst for a NAVTTC training center. You have exam scores for **10 students** across **4 subjects**. Your manager needs a complete analysis report.

Apply everything you learned today — do not use Python loops where NumPy operations can do the job.

In [ ]:
# ── SETUP: The Dataset ─────────────────────────────────────────────────────

import numpy as np

students = ["Ahmed", "Fatima", "Zara", "Hassan", "Sara",
            "Bilal", "Amina", "Tariq", "Khaled", "Zainab"]

subjects = ["Python", "Statistics", "Excel", "Presentation"]

# 10 students × 4 subjects
marks = np.array([
    [85, 78, 90, 88],    # Ahmed
    [92, 95, 88, 91],    # Fatima
    [70, 65, 75, 72],    # Zara
    [55, 58, 60, 52],    # Hassan
    [95, 98, 92, 96],    # Sara
    [62, 68, 70, 65],    # Bilal
    [88, 85, 91, 87],    # Amina
    [45, 50, 48, 42],    # Tariq
    [78, 82, 85, 79],    # Khaled
    [91, 90, 88, 94],    # Zainab
])

print(f"Dataset shape: {marks.shape}  ({marks.shape[0]} students × {marks.shape[1]} subjects)")
print(f"Total data points: {marks.size}")

In [ ]:
# ── PART 1: Student Performance ────────────────────────────────────────────

# Calculate each student's average (axis=1 → across columns)
student_avg = np.mean(marks, axis=1).round(2)

# Assign grades using np.where
grades = np.where(student_avg >= 90, "A",
         np.where(student_avg >= 80, "B",
         np.where(student_avg >= 70, "C",
         np.where(student_avg >= 60, "D", "F"))))

# Pass/Fail
status = np.where(student_avg >= 60, "PASS", "FAIL")

# Rank students (1 = highest)
rank_indices = np.argsort(student_avg)[::-1]

print("=" * 62)
print("             STUDENT PERFORMANCE REPORT")
print("=" * 62)
print(f"  {'RANK':<5} {'NAME':<10} {'AVG':>6} {'GRADE':>6} {'STATUS':>7}")
print("  " + "-" * 38)
for rank, idx in enumerate(rank_indices, 1):
    print(f"  {rank:<5} {students[idx]:<10} {student_avg[idx]:>6.2f} {grades[idx]:>6} {status[idx]:>7}")
print("=" * 62)

In [ ]:
# ── PART 2: Subject Analysis ───────────────────────────────────────────────

# Per-subject stats (axis=0 → down rows)
subj_avg = np.mean(marks, axis=0).round(2)
subj_min = np.min(marks, axis=0)
subj_max = np.max(marks, axis=0)
subj_std = np.std(marks, axis=0).round(2)

print("=" * 62)
print("                  SUBJECT ANALYSIS")
print("=" * 62)
print(f"  {'SUBJECT':<14} {'AVG':>6} {'MIN':>5} {'MAX':>5} {'STD':>6}")
print("  " + "-" * 40)
for i, subj in enumerate(subjects):
    print(f"  {subj:<14} {subj_avg[i]:>6.2f} {subj_min[i]:>5} {subj_max[i]:>5} {subj_std[i]:>6.2f}")
print("=" * 62)

# Hardest and easiest subject
hardest = subjects[np.argmin(subj_avg)]
easiest = subjects[np.argmax(subj_avg)]
print(f"  Hardest subject : {hardest} (avg {np.min(subj_avg):.2f})")
print(f"  Easiest subject : {easiest} (avg {np.max(subj_avg):.2f})")
print("=" * 62)

In [ ]:
# ── PART 3: Class Summary Statistics ──────────────────────────────────────

all_scores = marks.flatten()   # Convert 2D → 1D for overall stats

pass_count  = np.sum(student_avg >= 60)
fail_count  = np.sum(student_avg < 60)
distinction = np.sum(student_avg >= 90)

grade_vals, grade_counts = np.unique(grades, return_counts=True)

print("=" * 45)
print("         CLASS SUMMARY")
print("=" * 45)
print(f"  Total students  : {len(students)}")
print(f"  Class average   : {np.mean(student_avg):.2f}")
print(f"  Class median    : {np.median(student_avg):.2f}")
print(f"  Std deviation   : {np.std(student_avg):.2f}")
print(f"  Highest scorer  : {students[np.argmax(student_avg)]} ({np.max(student_avg):.2f})")
print(f"  Lowest scorer   : {students[np.argmin(student_avg)]} ({np.min(student_avg):.2f})")
print("-" * 45)
print(f"  Passed          : {pass_count} students")
print(f"  Failed          : {fail_count} students")
print(f"  Distinctions    : {distinction} students")
print("-" * 45)
print("  Grade Distribution:")
for g, c in zip(grade_vals, grade_counts):
    bar = "▓" * c
    print(f"    Grade {g}:  {bar} ({c})")
print("=" * 45)

---
## 📝 Day 25 Summary

### Creating Arrays:
| Function | Purpose | Example |
|---|---|---|
| `np.array([...])` | From a Python list | `np.array([1, 2, 3])` |
| `np.zeros(n)` | All zeros | `np.zeros((3,4))` |
| `np.ones(n)` | All ones | `np.ones(5)` |
| `np.arange(start,stop,step)` | Like range() | `np.arange(0, 10, 2)` |
| `np.linspace(start,stop,n)` | n evenly spaced | `np.linspace(0, 1, 5)` |
| `np.random.randint(lo,hi,n)` | Random integers | `np.random.randint(60, 100, 10)` |

### Key Attributes:
| Attribute | Returns |
|---|---|
| `.shape` | `(rows, cols)` — dimensions |
| `.ndim` | Number of dimensions |
| `.dtype` | Data type (int64, float64…) |
| `.size` | Total number of elements |

### Statistics:
| Function | What it does |
|---|---|
| `np.mean(arr)` | Average |
| `np.median(arr)` | Middle value |
| `np.std(arr)` | Spread around mean |
| `np.min()` / `np.max()` | Smallest / Largest |
| `np.sum(arr)` | Total |
| `np.percentile(arr, 75)` | 75th percentile |
| `np.argmin()` / `np.argmax()` | Index of min/max |

---

### 🏠 Homework:

1. Create a NumPy array of 12 monthly temperatures for Islamabad (make up realistic values in °C). Calculate mean, max, min, and std. Use boolean indexing to find which months were above 35°C.

2. Create a 5×3 random array of marks (50–100). Calculate the average per student (axis=1), average per subject (axis=0), and use `np.where()` to label each student as "Pass" or "Fail" (threshold: 65).

3. Given `sales = np.array([82000, 95000, 110000, 125000, 140000, 98000])` — apply a 12% commission to all sales above 100,000 and 8% to the rest using `np.where()`. Print original and commission values.

---
> 📌 **Next Session — Pandas:** Everything NumPy taught you about arrays becomes the foundation for Pandas DataFrames. You'll load real CSV files, filter rows, group data, and build full analysis pipelines.